select SUBJECT_NAME,PROFESSION_NAME
from Subject inner join (PUlPIT inner join ( FACULTY inner join PROFESSION
on FACULTY.FACULTY = PROFESSION.FACULTY
)
on PULPIT.FACULTY = FACULTY.FACULTY)
on SUBJECT.PULPIT = PULPIT.PULPIT
where PROFESSION_NAME = 'Ћесное хоз€йство'