select AUDITORIUM_TYPE.AUDITORIUM_TYPENAME, max(AUDITORIUM_CAPACITY),min(AUDITORIUM_CAPACITY),AVG(AUDITORIUM_CAPACITY),SUM(AUDITORIUM_CAPACITY),COUNT(*)
from AUDITORIUM inner join AUDITORIUM_TYPE on AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE and AUDITORIUM_CAPACITY>10
group by AUDITORIUM_TYPE.AUDITORIUM_TYPENAME