select PULPIT_NAME
from PULPIT,FACULTY
where PULPIT.FACULTY = FACULTY.FACULTY 
and 
FACULTY.FACULTY in (select PROFESSION.FACULTY from PROFESSION where (PROFESSION.PROFESSION_NAME like '%технологи%'))