select a.AUDITORIUM, a.AUDITORIUM_TYPE,a.AUDITORIUM_CAPACITY
from AUDITORIUM a
where a.AUDITORIUM_CAPACITY = 
(select top(1) a2.AUDITORIUM_CAPACITY from AUDITORIUM a2
where a2.AUDITORIUM_TYPE = a.AUDITORIUM_TYPE order by a2.AUDITORIUM_CAPACITY desc)
order by a.AUDITORIUM_CAPACITY desc;