select PULPIT_NAME,PROFESSION.PROFESSION_NAME
from pulpit inner join (
FACULTY inner join PROFESSION 
on FACULTY.FACULTY = PROFESSION.FACULTY
)
on PULPIT.FACULTY = FACULTY.FACULTY
where PROFESSION_NAME like '%технологи%'	